--
-- Create users
--
CREATE USER 'trucker1'@'localhost.localdomain' IDENTIFIED BY 'trucker';
GRANT ALL PRIVILEGES ON *.* TO 'trucker1'@'localhost.localdomain' WITH GRANT OPTION;

CREATE USER 'trucker1'@'%' IDENTIFIED BY 'trucker';
GRANT ALL PRIVILEGES ON *.* TO 'trucker1'@'%' WITH GRANT OPTION;

--
-- Create tables
--
CREATE TABLE DRIVERS (
  DRIVER_ID  VARCHAR(200) NOT NULL,
  DRIVER_NAME VARCHAR(1000) NOT NULL,
  CERTIFIED VARCHAR(10) NOT NULL,
  WAGE_PLAN VARCHAR(10) NOT NULL
);

CREATE TABLE TIMESHEET (
  DRIVER_ID  VARCHAR(200) NOT NULL,
  DRIVER_WEEK INT,
  HOURS_LOGGED BIGINT(100),
  MILES_LOGGED BIGINT(100)
);

--
-- Import data
--
LOAD DATA LOCAL INFILE 'drivers.csv' INTO TABLE DRIVERS
  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'timesheet.csv' INTO TABLE TIMESHEET
  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
