<!DOCTYPE html>
<!--
 | Generated by Apache Maven Doxia at 2015-06-22
 | Rendered using Apache Maven Fluido Skin 1.3.0
-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="Date-Revision-yyyymmdd" content="20150622" />
    <meta http-equiv="Content-Language" content="en" />
    <title>Metadata and Governance - Data Governance and Metadata framework for Hadoop</title>
    <link rel="stylesheet" href="./css/apache-maven-fluido-1.3.0.min.css" />
    <link rel="stylesheet" href="./css/site.css" />
    <link rel="stylesheet" href="./css/print.css" media="print" />

      
    <script type="text/javascript" src="./js/apache-maven-fluido-1.3.0.min.js"></script>

                          
        
<script type="text/javascript">$( document ).ready( function() { $( '.carousel' ).carousel( { interval: 3500 } ) } );</script>
          
            </head>
        <body class="topBarEnabled">
          
                        
                    
                

    <div id="topbar" class="navbar navbar-fixed-top ">
      <div class="navbar-inner">
                                  <div class="container" style="width: 68%;"><div class="nav-collapse">
            
                
                                <ul class="nav">
                          <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Atlas <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="index.html"  title="About">About</a>
</li>
                  
                      <li>      <a href="https://cwiki.apache.org/confluence/display/ATLAS"  title="Wiki">Wiki</a>
</li>
                  
                      <li>      <a href="https://cwiki.apache.org/confluence/display/ATLAS"  title="News">News</a>
</li>
                  
                      <li>      <a href="https://git-wip-us.apache.org/repos/asf/incubator-atlas.git"  title="Git">Git</a>
</li>
                  
                      <li>      <a href="https://svn.apache.org/repos/asf/incubator/atlas"  title="Svn">Svn</a>
</li>
                  
                      <li>      <a href="https://issues.apache.org/jira/browse/ATLAS"  title="Jira">Jira</a>
</li>
                  
                      <li>      <a href="https://cwiki.apache.org/confluence/display/ATLAS/PoweredBy"  title="Powered by">Powered by</a>
</li>
                  
                      <li>      <a href="http://blogs.apache.org/atlas/"  title="Blog">Blog</a>
</li>
                          </ul>
      </li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Project Information <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="project-info.html"  title="Summary">Summary</a>
</li>
                  
                      <li>      <a href="mail-lists.html"  title="Mailing Lists">Mailing Lists</a>
</li>
                  
                      <li>      <a href="http://webchat.freenode.net?channels=apacheatlas&uio=d4"  title="IRC">IRC</a>
</li>
                  
                      <li>      <a href="team-list.html"  title="Team">Team</a>
</li>
                  
                      <li>      <a href="issue-tracking.html"  title="Issue Tracking">Issue Tracking</a>
</li>
                  
                      <li>      <a href="source-repository.html"  title="Source Repository">Source Repository</a>
</li>
                  
                      <li>      <a href="license.html"  title="License">License</a>
</li>
                          </ul>
      </li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Releases <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="https://cwiki.apache.org/confluence/display/ATLAS"  title="Coming soon">Coming soon</a>
</li>
                          </ul>
      </li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="index.html"  title="current">current</a>
</li>
                          </ul>
      </li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="index.html"  title="Overview">Overview</a>
</li>
                  
                      <li>      <a href="QuickStart.html"  title="Getting Started">Getting Started</a>
</li>
                  
                      <li>      <a href="Architecture.html"  title="Architecture">Architecture</a>
</li>
                  
                      <li>      <a href="InstallationSteps.html"  title="Installation">Installation</a>
</li>
                  
                      <li>      <a href="TypeSystem.html"  title="Type System">Type System</a>
</li>
                  
                      <li>      <a href="Configuration.html"  title="Configuration">Configuration</a>
</li>
                  
                      <li>      <a href="Security.html"  title="Security">Security</a>
</li>
                  
                      <li>      <a href="api/rest.html"  title="Rest API">Rest API</a>
</li>
                          </ul>
      </li>
                <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">ASF <b class="caret"></b></a>
        <ul class="dropdown-menu">
        
                      <li>      <a href="http://www.apache.org/foundation/how-it-works.html"  title="How Apache Works">How Apache Works</a>
</li>
                  
                      <li>      <a href="http://www.apache.org/foundation/"  title="Foundation">Foundation</a>
</li>
                  
                      <li>      <a href="http://www.apache.org/foundation/sponsorship.html"  title="Sponsoring Apache">Sponsoring Apache</a>
</li>
                  
                      <li>      <a href="http://www.apache.org/foundation/thanks.html"  title="Thanks">Thanks</a>
</li>
                          </ul>
      </li>
                  </ul>
          
                      <form id="search-form" action="http://www.google.com/search" method="get"  class="navbar-search pull-right" >
    
  <input value="http://atlas.incubator.apache.org" name="sitesearch" type="hidden"/>
  <input class="search-query" name="q" id="query" type="text" />
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=search-form"></script>
          
                            
            
            
            
    <iframe src="http://www.facebook.com/plugins/like.php?href=http://atlas.incubator.apache.org/atlas-docs&send=false&layout=button_count&show-faces=false&action=like&colorscheme=dark"
        scrolling="no" frameborder="0"
        style="border:none; width:80px; height:20px; margin-top: 10px;"  class="pull-right" ></iframe>
                        
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

        <ul class="nav pull-right"><li style="margin-top: 10px;">
    
    <div class="g-plusone" data-href="http://atlas.incubator.apache.org/atlas-docs" data-size="medium"  width="60px" align="right" ></div>

        </li></ul>
                              
                   
                      </div>
          
        </div>
      </div>
    </div>
    
        <div class="container">
          <div id="banner">
        <div class="pull-left">
                                                  <a href=".." id="bannerLeft">
                                                                                                <img src="images/atlas-logo.png"  alt="Apache Atlas" width="200px" height="45px"/>
                </a>
                      </div>
        <div class="pull-right">                  <a href="http://incubator.apache.org" id="bannerRight">
                                                                                                <img src="images/apache-incubator-logo.png"  alt="Apache Incubator"/>
                </a>
      </div>
        <div class="clear"><hr/></div>
      </div>

      <div id="breadcrumbs">
        <ul class="breadcrumb">
                
                    
                              <li class="">
                    <a href="http://www.apache.org" class="externalLink" title="Apache">
        Apache</a>
        </li>
      <li class="divider ">/</li>
            <li class="">
                    <a href="index.html" title="Atlas">
        Atlas</a>
        </li>
      <li class="divider ">/</li>
        <li class="">Data Governance and Metadata framework for Hadoop</li>
        
                
                    
                  <li id="publishDate" class="pull-right">Last Published: 2015-06-22</li> <li class="divider pull-right">|</li>
              <li id="projectVersion" class="pull-right">Version: 0.6-incubating-SNAPSHOT</li>
            
                            </ul>
      </div>

      
                        
        <div id="bodyColumn" >
                                  
            <div class="section">
<h2>Data Governance and Metadata framework for Hadoop<a name="Data_Governance_and_Metadata_framework_for_Hadoop"></a></h2></div>
<div class="section">
<h3>Overview<a name="Overview"></a></h3>
<p>Atlas is a scalable and extensible set of core foundational governance services &#x2013; enabling enterprises to effectively and efficiently meet their compliance requirements within Hadoop and allows integration with the whole enterprise data ecosystem.</p></div>
<div class="section">
<h3>Features<a name="Features"></a></h3></div>
<div class="section">
<h4>Data Classification<a name="Data_Classification"></a></h4>
<p></p>
<ul>
<li>Import or define taxonomy business-oriented annotations for data</li>
<li>Define, annotate, and automate capture of relationships between data sets and underlying</li></ul>elements including source, target, and derivation processes
<ul>
<li>Export metadata to third-party systems</li></ul></div>
<div class="section">
<h4>Centralized Auditing<a name="Centralized_Auditing"></a></h4>
<p></p>
<ul>
<li>Capture security access information for every application, process, and interaction with data</li>
<li>Capture the operational information for execution, steps, and activities</li></ul></div>
<div class="section">
<h4>Search &amp; Lineage (Browse)<a name="Search__Lineage_Browse"></a></h4>
<p></p>
<ul>
<li>Pre-defined navigation paths to explore the data classification and audit information</li>
<li>Text-based search features locates relevant data and audit event across Data Lake quickly</li></ul>and accurately
<ul>
<li>Browse visualization of data set lineage allowing users to drill-down into operational,</li></ul>security, and provenance related information</div>
<div class="section">
<h4>Security &amp; Policy Engine<a name="Security__Policy_Engine"></a></h4>
<p></p>
<ul>
<li>Rationalize compliance policy at runtime based on data classification schemes, attributes</li></ul>and roles.
<ul>
<li>Advanced definition of policies for preventing data derivation based on classification</li></ul>(i.e. re-identification) &#x2013; Prohibitions
<ul>
<li>Column and Row level masking based on cell values and attibutes.</li></ul></div>
<div class="section">
<h3>Getting Started<a name="Getting_Started"></a></h3>
<p></p>
<ul>
<li><a href="./QuickStart.html">Quick Start Guide</a></li></ul></div>
<div class="section">
<h3>Documentation<a name="Documentation"></a></h3>
<p></p>
<ul>
<li><a href="./Architecture.html">High Level Architecture</a></li>
<li><a href="./TypeSystem.html">Type System</a></li>
<li><a href="./Repository.html">Metadata Repository</a></li>
<li><a href="./Search.html">Search</a></li>
<li><a href="./Security.html">security</a></li>
<li><a href="./Configuration.html">Configuration</a></li></ul></div>
<div class="section">
<h3>API Documentation<a name="API_Documentation"></a></h3>
<p></p>
<ul>
<li><a href="api/rest.html">REST API Documentation</a></li></ul>
<p><a name="LicenseInfo"></a></p></div>
<div class="section">
<h2>Licensing Information<a name="Licensing_Information"></a></h2>
<p>Metadata (Atlas) is distributed under <a class="externalLink" href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a>.</p></div>
                  </div>
          </div>

    <hr/>

    <footer>
            <div class="container">
              <div class="row span12">Copyright &copy;                    2015
                        <a href="http://www.apache.org">Apache Software Foundation</a>.
            All Rights Reserved.      
                    
      </div>

                          
                <p id="poweredBy" class="pull-right">
                          <a href="http://maven.apache.org/" title="Built by Maven" class="poweredBy">
        <img class="builtBy" alt="Built by Maven" src="./images/logos/maven-feather.png" />
      </a>
              </p>
        
                </div>
    </footer>
  </body>
</html>
